LevelsScale:
    type: entity
    table: levels_scale
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        description:
            type: string
            nullable: true
            length: 3000
            fixed: false
    lifecycleCallbacks: {  }
