Sex:
    type: entity
    table: sex
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        gender:
            type: string
            nullable: false
            length: 1
            fixed: false
        code:
            type: boolean
            nullable: false
        socialTitle:
            type: string
            nullable: false
            length: 15
            fixed: false
            column: social_title
        socialTitleAbbrev:
            type: string
            nullable: true
            length: 5
            fixed: false
            column: social_title_abbrev
    lifecycleCallbacks: {  }
