criterion:
    path:     /
    defaults: { _controller: "AppNotationBundle:Criterion:index" }

criterion_show:
    path:     /{id}/show
    defaults: { _controller: "AppNotationBundle:Criterion:show" }

criterion_new:
    path:     /new
    defaults: { _controller: "AppNotationBundle:Criterion:new" }

criterion_create:
    path:     /create
    defaults: { _controller: "AppNotationBundle:Criterion:create" }
    requirements: { _method: post }

criterion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppNotationBundle:Criterion:edit" }

criterion_update:
    path:     /{id}/update
    defaults: { _controller: "AppNotationBundle:Criterion:update" }
    requirements: { _method: post|put }

criterion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppNotationBundle:Criterion:delete" }
    requirements: { _method: post|delete }
