gradingDetail:
    path:     /
    defaults: { _controller: "AppNotationBundle:GradingDetail:index" }

gradingDetail_show:
    path:     /{id}/show
    defaults: { _controller: "AppNotationBundle:GradingDetail:show" }

gradingDetail_new:
    path:     /new
    defaults: { _controller: "AppNotationBundle:GradingDetail:new" }

gradingDetail_create:
    path:     /create
    defaults: { _controller: "AppNotationBundle:GradingDetail:create" }
    requirements: { _method: post }

gradingDetail_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppNotationBundle:GradingDetail:edit" }

gradingDetail_update:
    path:     /{id}/update
    defaults: { _controller: "AppNotationBundle:GradingDetail:update" }
    requirements: { _method: post|put }

gradingDetail_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppNotationBundle:GradingDetail:delete" }
    requirements: { _method: post|delete }
