level:
    path:     /
    defaults: { _controller: "AppNotationBundle:Level:index" }

level_show:
    path:     /{id}/show
    defaults: { _controller: "AppNotationBundle:Level:show" }

level_new:
    path:     /new
    defaults: { _controller: "AppNotationBundle:Level:new" }

level_create:
    path:     /create
    defaults: { _controller: "AppNotationBundle:Level:create" }
    requirements: { _method: post }

level_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppNotationBundle:Level:edit" }

level_update:
    path:     /{id}/update
    defaults: { _controller: "AppNotationBundle:Level:update" }
    requirements: { _method: post|put }

level_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppNotationBundle:Level:delete" }
    requirements: { _method: post|delete }
