period:
    path:     /
    defaults: { _controller: "AppNotationBundle:Period:index" }

period_show:
    path:     /{id}/show
    defaults: { _controller: "AppNotationBundle:Period:show" }

period_new:
    path:     /new
    defaults: { _controller: "AppNotationBundle:Period:new" }

period_create:
    path:     /create
    defaults: { _controller: "AppNotationBundle:Period:create" }
    requirements: { _method: post }

period_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppNotationBundle:Period:edit" }

period_update:
    path:     /{id}/update
    defaults: { _controller: "AppNotationBundle:Period:update" }
    requirements: { _method: post|put }

period_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppNotationBundle:Period:delete" }
    requirements: { _method: post|delete }
